/**
 * Bot Default Settings
 *
 * These defaults are copied from frontend form defaults to provide
 * a consistent baseline when creating bots via API.
 *
 * Source: main-dash-redesign/src/contexts/bots/form/formDefaults.ts
 *
 * Note: This creates intentional duplication between frontend and backend.
 * Keep in sync manually or consider generating from shared source.
 */

import {
  BaseSlOnEnum,
  BotMarginTypeEnum,
  BotSettings,
  BotStartTypeEnum,
  BotStatusEnum,
  CloseDCATypeEnum,
  ComboBotSettings,
  ComboTpBase,
  CooldownOptionsEnum,
  CooldownUnits,
  DCABotSettings,
  DCAConditionEnum,
  DCATypeEnum,
  DcaVolumeRequiredChangeRef,
  DCAVolumeType,
  DynamicPriceFilterDirectionEnum,
  DynamicPriceFilterPriceTypeEnum,
  FuturesStrategyEnum,
  OrderTypeEnum,
  PairPrioritizationEnum,
  RiskSlTypeEnum,
  RRSlTypeEnum,
  ScaleDcaTypeEnum,
  StrategyEnum,
  TerminalDealTypeEnum,
  VolumeValueEnum,
  BBCrossingEnum,
  CloseConditionEnum,
  DivTypeEnum,
  ECDTriggerEnum,
  ExchangeIntervals,
  IndicatorEnum,
  IndicatorsLogicEnum,
  IndicatorStartConditionEnum,
  MAEnum,
  OrderSizeTypeEnum,
  PCConditionEnum,
  ppValueEnum,
  ppValueTypeEnum,
  RangeType,
  rsiValue2Enum,
  rsiValueEnum,
  SettingsIndicators,
  SRCrossingEnum,
  StartConditionEnum,
  STConditionEnum,
  StochRangeEnum,
  TradingviewAnalysisConditionEnum,
  TradingviewAnalysisSignalEnum,
  TrendFilterOperatorEnum,
  DivergenceOscillators,
  SessionRuleEnum,
  LWValueEnum,
} from '../../../types'

export const DCA_FORM_DEFAULTS: DCABotSettings = {
  pair: ['BTC_USDT'],
  name: 'New Bot',
  strategy: StrategyEnum.long,
  profitCurrency: 'quote',
  baseOrderSize: '10',
  startOrderType: OrderTypeEnum.limit,
  startCondition: StartConditionEnum.asap,
  tpPerc: '1',
  orderFixedIn: 'quote',
  orderSize: '10',
  step: '1',
  gridLevel: '5',
  comboSmartGridsCount: '6',
  ordersCount: 5,
  activeOrdersCount: 1,
  volumeScale: '1',
  stepScale: '1',
  useTp: true,
  useSl: false,
  slPerc: '-10',
  baseSlOn: BaseSlOnEnum.avg,
  useSmartOrders: false,
  minOpenDeal: '',
  maxOpenDeal: '',
  useDca: true,
  hodlDay: '7',
  hodlAt: new Date(
    new Date(new Date().setHours(24, 0, 0, 0)).setHours(15, 0, 0, 0),
  ).toLocaleTimeString(),
  hodlNextBuy: new Date(new Date().setHours(24, 0, 0, 0)).getTime(),
  maxNumberOfOpenDeals: '1',
  indicators: [],
  indicatorGroups: [],
  orderSizeType: OrderSizeTypeEnum.quote,
  limitTimeout: '20',
  useLimitTimeout: false,
  cooldownAfterDealStart: false,
  cooldownAfterDealStartInterval: 1,
  cooldownAfterDealStartUnits: CooldownUnits.minutes,
  cooldownAfterDealStartOption: CooldownOptionsEnum.bot,
  cooldownAfterDealStop: false,
  cooldownAfterDealStopInterval: 1,
  cooldownAfterDealStopUnits: CooldownUnits.minutes,
  cooldownAfterDealStopOption: CooldownOptionsEnum.bot,
  moveSL: false,
  moveSLTrigger: '0.5',
  moveSLValue: '0.2',
  moveSLForAll: true,
  trailingSl: false,
  trailingTp: false,
  trailingTpPerc: '0.3',
  useCloseAfterX: false,
  closeAfterX: '20',
  useCloseAfterXloss: false,
  closeAfterXloss: '20',
  useCloseAfterXprofit: false,
  closeAfterXprofitCond: IndicatorStartConditionEnum.gt,
  closeAfterXprofitValue: '20',
  useCloseAfterXwin: false,
  closeAfterXwin: '20',
  useMulti: false,
  maxDealsPerPair: '1',
  useCloseAfterXopen: false,
  closeAfterXopen: '20',
  botStart: BotStartTypeEnum.manual,
  botActualStart: BotStartTypeEnum.manual,
  useBotController: false,
  stopType: CloseDCATypeEnum.leave,
  dealCloseCondition: CloseConditionEnum.tp,
  dealCloseConditionSL: CloseConditionEnum.tp,
  useMinTP: false,
  minTp: '1',
  closeDealType: CloseDCATypeEnum.closeByMarket,
  useMultiTp: false,
  multiTp: [],
  useMultiSl: false,
  multiSl: [],
  marginType: BotMarginTypeEnum.isolated,
  leverage: 1,
  futures: false,
  coinm: false,
  useVolumeFilter: false,
  volumeTop: '500',
  volumeValue: VolumeValueEnum.top25,
  baseStep: '1',
  baseGridLevels: '5',
  useActiveMinigrids: false,
  comboActiveMinigrids: '1',
  dcaCondition: DCAConditionEnum.percentage,
  scaleDcaType: ScaleDcaTypeEnum.percentage,
  closeByTimer: false,
  closeByTimerValue: 10,
  closeByTimerUnits: CooldownUnits.minutes,
  useRelativeVolumeFilter: false,
  relativeVolumeTop: '500',
  relativeVolumeValue: VolumeValueEnum.top25,
  feeOrder: true,
  useMaxDealsPerHigherTimeframe: true,
  maxDealsPerHigherTimeframe: '1',
  ignoreStartDeals: false,
  comboTpBase: ComboTpBase.filled,
  dynamicPriceFilterDeviation: '1',
  dynamicPriceFilterPriceType: DynamicPriceFilterPriceTypeEnum.entry,
  dynamicPriceFilterDirection: DynamicPriceFilterDirectionEnum.under,
  pairPrioritization: PairPrioritizationEnum.alphabetical,
  riskSlType: RiskSlTypeEnum.perc,
  riskSlAmountPerc: '2',
  riskSlAmountValue: '10',
  riskUseTpRatio: true,
  riskTpRatio: '1.5',
  riskMaxPositionSize: '-1',
  riskMinPositionSize: '0',
  dynamicArLockValue: true,
  reinvestValue: '50',
  riskReductionValue: '50',
  useRiskReduction: false,
  useReinvest: false,
  startBotPriceCondition: IndicatorStartConditionEnum.gt,
  stopBotPriceCondition: IndicatorStartConditionEnum.gt,
  type: DCATypeEnum.regular,
  useNoOverlapDeals: false,
  minimumDeviation: '1',
  skipBalanceCheck: false,
  dcaVolumeBaseOn: DCAVolumeType.scale,
  dcaVolumeRequiredChange: '5',
  dcaVolumeRequiredChangeRef: DcaVolumeRequiredChangeRef.tp,
  dcaVolumeMaxValue: '-1',
  dcaCustom: [],
  baseOrderPrice: '0',
  useLimitPrice: false,
  hodlHourly: false,
  notUseLimitReposition: false,
  stopStatus: BotStatusEnum.closed,
  terminalDealType: TerminalDealTypeEnum.smart,
  importFrom: '',
  useFixedTPPrices: false,
  useFixedSLPrices: false,
  fixedTpPrice: '',
  fixedSlPrice: '',
  comboSlLimit: false,
  comboTpLimit: false,
  remainderFullAmount: false,
  autoRebalancing: false,
  adaptiveClose: false,
  useStaticPriceFilter: false,
  useCooldown: false,
  useDynamicPriceFilter: false,
  useVolumeFilterAll: false,
  dynamicPriceFilterOverValue: '5',
  dynamicPriceFilterUnderValue: '5',
  useRiskReward: false,
  riskMaxSl: '-100',
  riskMinSl: '0',
  comboUseSmartGrids: false,
  startDealLogic: IndicatorsLogicEnum.and,
  stopDealLogic: IndicatorsLogicEnum.and,
  stopBotLogic: IndicatorsLogicEnum.and,
  startBotLogic: IndicatorsLogicEnum.and,
  startBotPriceValue: '',
  stopDealSlLogic: IndicatorsLogicEnum.and,
  stopBotPriceValue: '',
  closeOrderType: OrderTypeEnum.limit,
  rrSlType: RRSlTypeEnum.indicator,
  rrSlFixedValue: '2',
  useSeparateMaxDealsOverAndUnder: false,
  maxDealsOver: '1',
  maxDealsUnder: '1',
  useSeparateMaxDealsOverAndUnderPerSymbol: false,
  maxDealsOverPerSymbol: '1',
  maxDealsUnderPerSymbol: '1',
  dcaByMarket: false,
}

export const COMBO_FORM_DEFAULTS: ComboBotSettings = {
  ...DCA_FORM_DEFAULTS,
  baseOrderSize: '500',
  orderSize: '500',
  startOrderType: OrderTypeEnum.market,
  tpPerc: '5',
  step: '5',
  useTp: false,
  slPerc: '-25',
  gridLevel: '5',
}

export const GRID_FORM_DEFAULTS: BotSettings = {
  name: 'New Grid Bot',
  pair: 'BTC_USDT',
  topPrice: 0,
  lowPrice: 0,
  levels: 10,
  gridStep: 1,
  budget: 0,
  useOrderInAdvance: false,
  prioritize: 'level',
  profitCurrency: 'quote',
  orderFixedIn: 'quote',
  sellDisplacement: 0,
  gridType: 'geometric',
  tpSl: false,
  tpSlCondition: 'valueChanged',
  tpPerc: 20,
  slPerc: -20,
  tpTopPrice: 0,
  slLowPrice: 0,
  tpSlAction: 'stop',
  slCondition: 'valueChanged',
  slAction: 'stop',
  useStartPrice: false,
  marginType: BotMarginTypeEnum.isolated,
  leverage: 1,
  futures: false,
  coinm: false,
  newProfit: true,
  strategy: StrategyEnum.long,
  futuresStrategy: FuturesStrategyEnum.neutral,
  updatedBudget: true,
  feeOrder: true,
  ordersInAdvance: 6,
  tpSlLimit: false,
  slLimit: false,
  sl: false,
  startPrice: '',
  skipBalanceCheck: false,
}

export const base = {
  indicatorCondition: IndicatorStartConditionEnum.cd,
  indicatorInterval: ExchangeIntervals.oneH,
  minPercFromLast: '1',
  keepConditionBars: '0',
  percentile: false,
  percentileLookback: 150,
  trendFilter: false,
  trendFilterLookback: 10,
  trendFilterType: TrendFilterOperatorEnum.lower,
  trendFilterValue: 2,
}

export const defDivergenceOscillators = [
  IndicatorEnum.cci,
  IndicatorEnum.mfi,
  IndicatorEnum.rsi,
  IndicatorEnum.wr,
  IndicatorEnum.macd,
  IndicatorEnum.uo,
  IndicatorEnum.ao,
  IndicatorEnum.mom,
  IndicatorEnum.stoch,
].sort((a, b) => a.localeCompare(b)) as DivergenceOscillators[]

export const indicatorConfigDefaults: {
  [x in IndicatorEnum]: Omit<
    SettingsIndicators,
    'uuid' | 'type' | 'indicatorAction' | 'groupId'
  >
} = {
  [IndicatorEnum.mar]: {
    indicatorLength: 7,
    indicatorValue: '0.99',
    mar1length: 20,
    mar1type: MAEnum.ema,
    mar2type: MAEnum.price,
    mar2length: 20,
    ...base,
  },
  [IndicatorEnum.rsi]: {
    indicatorLength: 7,
    indicatorValue: '70',
    ...base,
  },
  [IndicatorEnum.xo]: {
    indicatorLength: 7,
    indicatorValue: '70',
    xOscillator1: IndicatorEnum.rsi,
    xOscillator2: IndicatorEnum.mfi,
    xOscillator2length: 14,
    xOscillator2Interval: base.indicatorInterval,
    ...base,
  },
  [IndicatorEnum.ecd]: {
    indicatorLength: 7,
    indicatorValue: '70',
    ecdTrigger: ECDTriggerEnum.both,
    ...base,
  },
  [IndicatorEnum.bbwp]: {
    indicatorLength: 13,
    indicatorValue: '50',
    bbwpLookback: 252,
    momSource: 'close',
    ...base,
  },
  [IndicatorEnum.mom]: {
    indicatorLength: 10,
    indicatorValue: '70',
    momSource: 'close',
    ...base,
  },
  [IndicatorEnum.uo]: {
    indicatorLength: 7,
    indicatorValue: '70',
    uoFast: 7,
    uoMiddle: 14,
    uoSlow: 28,
    ...base,
  },
  [IndicatorEnum.wr]: {
    indicatorLength: 14,
    indicatorValue: '-40',
    ...base,
  },
  [IndicatorEnum.cci]: {
    indicatorLength: 20,
    indicatorValue: '100',
    ...base,
  },
  [IndicatorEnum.ao]: {
    indicatorLength: 20,
    indicatorValue: '0',
    ...base,
  },
  [IndicatorEnum.vo]: {
    indicatorLength: 7,
    indicatorValue: '0',
    voShort: 5,
    voLong: 10,
    ...base,
  },
  [IndicatorEnum.mfi]: {
    ...base,
    indicatorLength: 14,
    indicatorValue: '70',
  },
  [IndicatorEnum.adx]: {
    indicatorLength: 14,
    indicatorValue: '20',
    ...base,
  },
  [IndicatorEnum.bbw]: {
    indicatorLength: 20,
    indicatorValue: '0.05',
    bbwMa: MAEnum.sma,
    bbwMaLength: 20,
    bbwMult: 2,
    ...base,
  },
  [IndicatorEnum.bbpb]: {
    indicatorLength: 20,
    indicatorValue: '0.05',
    bbwMa: MAEnum.sma,
    bbwMaLength: 20,
    bbwMult: 2,
    ...base,
  },
  [IndicatorEnum.bb]: {
    ...base,
    indicatorLength: 20,
    indicatorValue: '0',
    bbCrossingValue: BBCrossingEnum.lower,
    indicatorCondition: IndicatorStartConditionEnum.cu,
    bbwMa: MAEnum.sma,
    bbwMaLength: 20,
    bbwMult: 2,
  },
  [IndicatorEnum.macd]: {
    indicatorLength: 9,
    indicatorValue: '0',
    macdFast: 12,
    macdSlow: 26,
    macdMaSignal: MAEnum.ema,
    macdMaSource: MAEnum.ema,
    ...base,
  },
  [IndicatorEnum.div]: {
    indicatorLength: 9,
    indicatorValue: '0',
    divMinCount: 2,
    divOscillators: defDivergenceOscillators,
    divType: DivTypeEnum.abear,
    ...base,
  },
  [IndicatorEnum.ma]: {
    indicatorLength: 20,
    indicatorValue: '0',
    maType: MAEnum.ema,
    maCrossingValue: MAEnum.price,
    maCrossingInterval: base.indicatorInterval,
    maCrossingLength: 20,
    ...base,
  },
  [IndicatorEnum.tv]: {
    indicatorLength: 15,
    indicatorValue: '0',
    signal: TradingviewAnalysisSignalEnum.strongBuy,
    condition: TradingviewAnalysisConditionEnum.entry,
    checkLevel: 15,
    ...base,
  },
  [IndicatorEnum.stoch]: {
    ...base,
    indicatorLength: 14,
    indicatorValue: '0',
    stochSmoothD: 3,
    stochSmoothK: 1,
    stochUpper: '80',
    stochLower: '20',
    valueInsteadof: 1,
    rsiValue: rsiValueEnum.k,
    rsiValue2: rsiValue2Enum.d,
    stochRange: StochRangeEnum.lower,
  },
  [IndicatorEnum.stochRSI]: {
    ...base,
    indicatorLength: 14,
    indicatorValue: '0',
    stochSmoothD: 3,
    stochSmoothK: 3,
    valueInsteadof: 1,
    stochUpper: '80',
    stochLower: '20',
    stochRSI: 14,
    rsiValue: rsiValueEnum.k,
    rsiValue2: rsiValue2Enum.d,
    stochRange: StochRangeEnum.lower,
    // rsiValue2: rsiValue2Enum2.k,
  },
  [IndicatorEnum.sr]: {
    ...base,
    indicatorValue: '0',
    srCrossingValue: SRCrossingEnum.resistance,
    indicatorLength: 1,
    leftBars: 15,
    rightBars: 15,
  },
  [IndicatorEnum.qfl]: {
    ...base,
    indicatorLength: 1,
    indicatorValue: '0',
    basePeriods: 36,
    pumpPeriods: 8,
    pump: 3,
    baseCrack: 3,
  },
  [IndicatorEnum.psar]: {
    ...base,
    indicatorLength: 1,
    indicatorValue: '0',
    psarInc: 0.02,
    psarMax: 0.2,
    psarStart: 0.02,
  },
  [IndicatorEnum.st]: {
    ...base,
    indicatorLength: 1,
    indicatorValue: '0',
    factor: 3,
    atrLength: 10,
    stCondition: STConditionEnum.up,
  },
  [IndicatorEnum.pc]: {
    ...base,
    indicatorLength: 1,
    indicatorValue: '1',
    pcUp: '5',
    pcDown: '5',
    pcCondition: PCConditionEnum.up,
    pcValue: '5',
  },
  [IndicatorEnum.atr]: {
    ...base,
    indicatorLength: 14,
    indicatorValue: '70',
  },
  [IndicatorEnum.pp]: {
    ...base,
    indicatorLength: 1,
    indicatorValue: '0',
    ppHighLeft: 5,
    ppHighRight: 5,
    ppLowLeft: 5,
    ppLowRight: 5,
    ppMult: 1,
    ppValue: ppValueEnum.anyL,
    ppType: ppValueTypeEnum.price,
  },
  [IndicatorEnum.adr]: {
    ...base,
    indicatorLength: 14,
    indicatorValue: '0',
  },
  [IndicatorEnum.ath]: {
    ...base,
    indicatorValue: '10',
    indicatorLength: 14,
    athLookback: 100,
  },
  [IndicatorEnum.kc]: {
    ...base,
    indicatorLength: 20,
    indicatorValue: '0',
    bbCrossingValue: BBCrossingEnum.lower,
    indicatorCondition: IndicatorStartConditionEnum.cu,
    kcMa: MAEnum.ema,
    bbwMult: 2,
    kcRange: RangeType.atr,
    kcRangeLength: 10,
  },
  [IndicatorEnum.unpnl]: {
    indicatorLength: 1,
    indicatorValue: '1',
    unpnlValue: 2,
    unpnlCondition: IndicatorStartConditionEnum.gt,
    ...base,
  },
  [IndicatorEnum.dc]: {
    indicatorLength: 20,
    indicatorValue: '0',
    ...base,
  },
  [IndicatorEnum.bullBear]: {
    indicatorLength: 20,
    indicatorValue: '0',
    ...base,
  },
  [IndicatorEnum.ic]: {
    indicatorLength: 20,
    indicatorValue: '0',
    ...base,
  },
  [IndicatorEnum.obfvg]: {
    indicatorLength: 20,
    indicatorValue: '0',
    ...base,
  },
  [IndicatorEnum.kcpb]: {
    indicatorLength: 20,
    indicatorValue: '0',
    ...base,
  },
  [IndicatorEnum.lw]: {
    indicatorLength: 20,
    indicatorValue: '0',
    lwThreshold: 2,
    lwMaxDuration: 1000,
    lwValue: LWValueEnum.any,
    ...base,
  },
  [IndicatorEnum.session]: {
    indicatorLength: 20,
    indicatorValue: '0',
    sessionDays: [1, 2, 3, 4, 5],
    sessionRule: SessionRuleEnum.in,
    ...base,
  },
}
